# Generated by Django 5.0.2 on 2025-09-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('stopped', 'Stopped'), ('done', 'Done')], default='running', max_length=20),
        ),
        migrations.AlterField(
            model_name='target',
            name='achieved_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='target',
            name='failed_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
