# Generated by Django 5.0.2 on 2025-09-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_target_status_alter_target_achieved_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('total_errors', models.IntegerField()),
                ('class_counts', models.JSONField()),
                ('quality', models.CharField(max_length=50)),
                ('threshold', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
